seed:
    2023
zeromask_scaling_factors:
    [0, 0]
n_generations:
    10
n_population:
    2
n_parents:
    2
n_offspring:
    2
parent_selection:
    roulette_wheel_rank
parent_rank:
    rank_non_dominated_fronts
survivor_selection:
    select_by_rank
survivor_rank:
    rank_is_dominated
crossover:
    uniform_crossover
crossover_mixing:
    0.5
mutations:
    [swap_mutation, uniform_integer_mutation, flip_mutation]
mutation_rates:
    [0.5, 0.5, 0.5]
n_allowed_duplicates:
    0
n_ligands:
    4
metal_center:
    Pd
oxidation_state:
    2
coordination_geometry:
    sqp
allowed_charges:
    [2]